FROM anapsix/alpine-java
LABEL maintainer="rahulwankhade92@gmail.com"
COPY /target/websocket-demo-0.0.1-SNAPSHOT.war /home/websocket-demo-0.0.1-SNAPSHOT.war
CMD ["java","-jar","/home/websocket-demo-0.0.1-SNAPSHOT.war"]